function GloveDefectGUI()
% GloveDefectGUI  Professional Glove Defect Detection Interface
%
% Features:
%   - Load image via file browser
%   - Full GDD pipeline (detectGloveType -> segmentGlove -> analyzeGlove)
%   - Side-by-side original vs annotated result
%   - Glove type display with full material name
%   - Defect confidence gauge (animated progress bar)
%   - PASS/FAIL verdict display

% Colour palette
BG      = [0.12 0.14 0.18];
PANEL   = [0.16 0.19 0.24];
ACCENT  = [0.18 0.52 0.90];
GREEN   = [0.18 0.80 0.44];
RED     = [0.95 0.30 0.30];
TEXT    = [0.92 0.94 0.97];
SUBTEXT = [0.55 0.60 0.68];
WHITE   = [1.00 1.00 1.00];
DARK    = [0.10 0.12 0.16];

fig = figure('Name', 'GDD - Glove Defect Detection System', ...
    'NumberTitle', 'off', ...
    'Color', BG, ...
    'Position', [60 60 1320 780], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Resize',  'on', ...
    'CloseRequestFcn', @onClose);

% =========================================================
% Header bar
% =========================================================
uipanel('Parent', fig, ...
    'BackgroundColor', DARK, ...
    'BorderType', 'none', ...
    'Units', 'normalized', ...
    'Position', [0 0.93 1 0.07]);

uicontrol('Parent', fig, 'Style', 'text', ...
    'String', 'GDD  |  Glove Defect Detection System', ...
    'FontSize', 16, 'FontWeight', 'bold', ...
    'ForegroundColor', WHITE, 'BackgroundColor', DARK, ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', 'Position', [0.02 0.935 0.60 0.050]);

uicontrol('Parent', fig, 'Style', 'text', ...
    'String', 'APU  CT036-3-IPPR', ...
    'FontSize', 10, ...
    'ForegroundColor', SUBTEXT, 'BackgroundColor', DARK, ...
    'HorizontalAlignment', 'right', ...
    'Units', 'normalized', 'Position', [0.70 0.940 0.28 0.038]);

% =========================================================
% Left control panel
% =========================================================
ctrlPanel = uipanel('Parent', fig, ...
    'BackgroundColor', PANEL, ...
    'BorderType', 'none', ...
    'Units', 'normalized', ...
    'Position', [0.01 0.02 0.22 0.90]);

% --- Load Image ---
makeLabel(ctrlPanel, 'INPUT IMAGE', 0.912, SUBTEXT, PANEL);

btnLoad = uicontrol('Parent', ctrlPanel, 'Style', 'pushbutton', ...
    'String', '  Browse Image...', ...
    'FontSize', 11, 'FontWeight', 'bold', ...
    'ForegroundColor', WHITE, 'BackgroundColor', ACCENT, ...
    'Units', 'normalized', 'Position', [0.06 0.855 0.88 0.052], ...
    'Callback', @loadImage);

lblFile = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', 'No image loaded', ...
    'FontSize', 8, ...
    'ForegroundColor', SUBTEXT, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.05 0.808 0.90 0.038]);

makeLine(ctrlPanel, 0.795);

% --- Glove Type ---
makeLabel(ctrlPanel, 'GLOVE TYPE', 0.768, SUBTEXT, PANEL);

lblGloveType = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', '--', ...
    'FontSize', 15, 'FontWeight', 'bold', ...
    'ForegroundColor', ACCENT, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.04 0.698 0.92 0.062]);

lblGloveConf = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', 'Type confidence: --', ...
    'FontSize', 8, ...
    'ForegroundColor', SUBTEXT, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.04 0.665 0.92 0.030]);

makeLine(ctrlPanel, 0.650);

% --- Defect ---
makeLabel(ctrlPanel, 'DEFECT DETECTED', 0.623, SUBTEXT, PANEL);

lblDefectName = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', '--', ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'ForegroundColor', WHITE, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.04 0.548 0.92 0.068]);

% --- Confidence Gauge ---
makeLabel(ctrlPanel, 'CONFIDENCE', 0.528, SUBTEXT, PANEL);

% Track background
uipanel('Parent', ctrlPanel, ...
    'BackgroundColor', [0.22 0.26 0.32], ...
    'BorderType', 'none', ...
    'Units', 'normalized', ...
    'Position', [0.06 0.492 0.88 0.028]);

% Gauge fill bar
hGaugeFill = uipanel('Parent', ctrlPanel, ...
    'BackgroundColor', GREEN, ...
    'BorderType', 'none', ...
    'Units', 'normalized', ...
    'Position', [0.06 0.492 0.001 0.028]);

lblConfPct = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', '0%', ...
    'FontSize', 11, 'FontWeight', 'bold', ...
    'ForegroundColor', WHITE, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.04 0.455 0.92 0.032]);

makeLine(ctrlPanel, 0.438);

% --- Verdict ---
makeLabel(ctrlPanel, 'VERDICT', 0.412, SUBTEXT, PANEL);

lblVerdict = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', '--', ...
    'FontSize', 24, 'FontWeight', 'bold', ...
    'ForegroundColor', SUBTEXT, 'BackgroundColor', PANEL, ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.04 0.335 0.92 0.072]);

makeLine(ctrlPanel, 0.320);

% --- Analyse button ---
btnAnalyse = uicontrol('Parent', ctrlPanel, 'Style', 'pushbutton', ...
    'String', '  ANALYSE', ...
    'FontSize', 13, 'FontWeight', 'bold', ...
    'ForegroundColor', WHITE, 'BackgroundColor', [0.20 0.22 0.28], ...
    'Units', 'normalized', 'Position', [0.06 0.248 0.88 0.062], ...
    'Callback', @runAnalysis, ...
    'Enable', 'off');

% --- Status bar ---
lblStatus = uicontrol('Parent', ctrlPanel, 'Style', 'text', ...
    'String', 'Ready -- load an image to begin', ...
    'FontSize', 8, ...
    'ForegroundColor', SUBTEXT, 'BackgroundColor', [0.13 0.15 0.19], ...
    'HorizontalAlignment', 'center', ...
    'Units', 'normalized', 'Position', [0.0 0.0 1.0 0.055]);

% =========================================================
% Image panels
% =========================================================
origPanel = uipanel('Parent', fig, ...
    'BackgroundColor', DARK, ...
    'Title', ' Original Image ', ...
    'ForegroundColor', SUBTEXT, ...
    'FontSize', 9, ...
    'BorderType', 'line', 'HighlightColor', [0.22 0.26 0.32], ...
    'Units', 'normalized', ...
    'Position', [0.245 0.02 0.365 0.90]);

axOrig = axes('Parent', origPanel, ...
    'Color', DARK, ...
    'XColor', 'none', 'YColor', 'none', ...
    'Units', 'normalized', 'Position', [0.02 0.02 0.96 0.96]);
axis(axOrig, 'off');

resultPanel = uipanel('Parent', fig, ...
    'BackgroundColor', DARK, ...
    'Title', ' Detection Result ', ...
    'ForegroundColor', SUBTEXT, ...
    'FontSize', 9, ...
    'BorderType', 'line', 'HighlightColor', [0.22 0.26 0.32], ...
    'Units', 'normalized', ...
    'Position', [0.625 0.02 0.365 0.90]);

axResult = axes('Parent', resultPanel, ...
    'Color', DARK, ...
    'XColor', 'none', 'YColor', 'none', ...
    'Units', 'normalized', 'Position', [0.02 0.02 0.96 0.96]);
axis(axResult, 'off');

% =========================================================
% State
% =========================================================
imgData = [];

% =========================================================
% Callbacks
% =========================================================

    function loadImage(~, ~)
        [fname, fpath] = uigetfile( ...
            {'*.png;*.jpg;*.jpeg;*.bmp;*.tif', 'Image Files'}, ...
            'Select Glove Image');
        if isequal(fname, 0), return; end

        imgData = imread(fullfile(fpath, fname));

        axes(axOrig);
        imshow(imgData, 'Parent', axOrig);
        axis(axOrig, 'off');
        cla(axResult);
        axis(axResult, 'off');

        shortName = fname;
        if length(shortName) > 32
            shortName = ['...' shortName(end-29:end)];
        end
        set(lblFile,       'String', shortName);
        set(lblGloveType,  'String', '--');
        set(lblGloveConf,  'String', 'Type confidence: --');
        set(lblDefectName, 'String', '--');
        set(lblConfPct,    'String', '0%');
        set(lblVerdict,    'String', '--', 'ForegroundColor', SUBTEXT);
        set(hGaugeFill,    'Position', [0.06 0.492 0.001 0.028]);
        set(btnAnalyse,    'Enable', 'on', 'BackgroundColor', ACCENT);
        set(lblStatus,     'String', 'Image loaded -- click ANALYSE');
        drawnow;
    end

    function runAnalysis(~, ~)
        if isempty(imgData)
            set(lblStatus, 'String', 'No image loaded.');
            return;
        end

        set(btnAnalyse,    'Enable', 'off', 'BackgroundColor', [0.20 0.22 0.28]);
        set(lblStatus,     'String', 'Analysing -- please wait...');
        set(lblVerdict,    'String', 'Running...', 'ForegroundColor', SUBTEXT);
        drawnow;

        try
            results = analyzeGlove(imgData);
        catch ME
            set(lblStatus,  'String', ['Error: ' ME.message]);
            set(btnAnalyse, 'Enable', 'on', 'BackgroundColor', ACCENT);
            return;
        end

        % Glove type
        gtStr  = gloveTypeName(results.gloveType);
        gtConf = round(results.typeConf * 100);
        gtCol  = gloveTypeColour(results.gloveType, ACCENT);
        set(lblGloveType, 'String', gtStr,  'ForegroundColor', gtCol);
        set(lblGloveConf, 'String', sprintf('Type confidence: %d%%', gtConf));

        % Defect
        if results.isDefect
            dConf    = results.defectConf;
            dName    = results.defectType;
            dConfPct = round(dConf * 100);
            dCol     = results.color;
            set(lblDefectName, 'String', upper(dName), 'ForegroundColor', dCol);
            set(lblConfPct,    'String', sprintf('%d%%', dConfPct));
            set(lblVerdict,    'String', 'FAIL', 'ForegroundColor', RED);
            animateGauge(hGaugeFill, dConf, dCol);
        else
            set(lblDefectName, 'String', 'None Detected', 'ForegroundColor', GREEN);
            set(lblConfPct,    'String', '--');
            set(lblVerdict,    'String', 'PASS', 'ForegroundColor', GREEN);
            set(hGaugeFill,    'Position', [0.06 0.492 0.001 0.028]);
        end

        % Draw result image
        axes(axResult);
        imshow(imgData, 'Parent', axResult);
        hold(axResult, 'on');

        % Glove mask tint
        if isfield(results, 'mask') && ~isempty(results.mask)
            [mr, mc] = size(results.mask);
            overlay  = zeros(mr, mc, 3);
            tc = gloveTypeColour(results.gloveType, ACCENT);
            overlay(:,:,1) = tc(1);
            overlay(:,:,2) = tc(2);
            overlay(:,:,3) = tc(3);
            hOv = imshow(overlay, 'Parent', axResult);
            set(hOv, 'AlphaData', double(results.mask) * 0.12);
        end

        % Simple clean bounding box with label centered above
        if results.isDefect && ~isempty(results.bbox)
            bb   = results.bbox;
            bCol = results.color;

            % Plain rectangle bounding box
            rectangle('Parent', axResult, ...
                'Position', bb, ...
                'EdgeColor', bCol, ...
                'LineWidth', 3);

            % Label centered above the box
            lx = bb(1) + bb(3)/2;
            ly = bb(2) - 12;
            if ly < 12
                ly = bb(2) + bb(4) + 18;
            end
            % Fixed font size -- change this single number to adjust label size
            scaledFont = 6;   % <-- adjust this (6=small, 8=medium, 10=large)
            text(lx, ly, ...
                sprintf('%s (%d%%)', upper(results.defectType), round(results.defectConf*100)), ...
                'Parent', axResult, ...
                'Color', bCol, ...
                'FontSize', scaledFont, 'FontWeight', 'bold', ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'bottom', ...
                'BackgroundColor', [0 0 0 0.60], ...
                'Margin', 4);
        end

        hold(axResult, 'off');
        axis(axResult, 'off');

        set(lblStatus, 'String', sprintf('Done  |  %s  |  %s  |  Conf: %d%%', ...
            gtStr, upper(results.verdict), round(results.defectConf * 100)));
        set(btnAnalyse, 'Enable', 'on', 'BackgroundColor', ACCENT);
        drawnow;
    end

    function onClose(~, ~)
        delete(fig);
    end

    function animateGauge(hFill, conf, col)
        targetW = 0.88 * conf;
        steps   = 20;
        for k = 1:steps
            w = targetW * (k / steps);
            set(hFill, 'Position', [0.06 0.492 max(w, 0.001) 0.028], ...
                'BackgroundColor', col);
            drawnow limitrate;
            pause(0.012);
        end
    end

end % GloveDefectGUI


% =========================================================
% Helper functions
% =========================================================

function name = gloveTypeName(gType)
switch lower(gType)
    case 'white',  name = 'White Latex Glove';
    case 'black',  name = 'Black Nitrile Glove';
    case 'blue',   name = 'Blue Nitrile Glove';
    case 'cotton', name = 'Cotton Work Glove';
    otherwise,     name = upper(gType);
end
end

function col = gloveTypeColour(gType, defaultCol)
switch lower(gType)
    case 'white',  col = [0.90 0.90 0.90];
    case 'black',  col = [0.75 0.75 0.80];
    case 'blue',   col = [0.20 0.60 1.00];
    case 'cotton', col = [0.85 0.70 0.45];
    otherwise,     col = defaultCol;
end
end

function makeLabel(parent, txt, ypos, col, bg)
uicontrol('Parent', parent, 'Style', 'text', ...
    'String', txt, ...
    'FontSize', 7, 'FontWeight', 'bold', ...
    'ForegroundColor', col, 'BackgroundColor', bg, ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Position', [0.06 ypos 0.88 0.022]);
end

function makeLine(parent, ypos)
uipanel('Parent', parent, ...
    'BackgroundColor', [0.22 0.26 0.32], ...
    'BorderType', 'none', ...
    'Units', 'normalized', ...
    'Position', [0.04 ypos 0.92 0.003]);
end